### ISSUE TITLE
Not working; instant suspension

### ISSUE THREAD

**Issue by Brent3784** [GermanicPanzer/copied-hacks#1]
When I used it, it did not work;I got an instant 3 week suspension
![68A83A6A-3327-4375-B31F-09709E6B13AD_1_105_c](https://github.com/GermanicPanzer/minesraft-blooket-hacks/assets/128167324/c12de15e-7ce2-4e3c-ad02-b05855e21756)

**Comment by GermanicPanzer** [comment]
oof forgot to say it doesnt work any more im sorry, i was really inactive, anyways i cant fix this but i found a repo where the same GUI actually works here -----> https://github.com/Shploop/Blooket-Cheats/blob/main/cheats/gui.js
